use_frameworks!

target 'CSPHeader_Example' do
  pod 'CSPHeader', :path => '../'

  target 'CSPHeader_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
