platform :ios, '9.0'

use_frameworks!

target 'CSPHeader_Example' do
  pod 'CSPHeader', :path => '../'

  target 'CSPHeader_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 3.0'
    pod 'Nimble', '~> 9.0'
  end
end
