platform :ios, '8.0'

use_frameworks!

target 'CSPHeader_Example' do
  pod 'CSPHeader', :path => '../'

  target 'CSPHeader_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3'
    pod 'Nimble', '~> 7.3'
  end
end
